//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace windowform.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        windowform.ServiceReference1.ModificarPersonaResponse ModificarPersona(windowform.ServiceReference1.ModificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<windowform.ServiceReference1.ModificarPersonaResponse> ModificarPersonaAsync(windowform.ServiceReference1.ModificarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPersona", ReplyAction="*")]
        windowform.ServiceReference1.AgregarPersonaResponse AgregarPersona(windowform.ServiceReference1.AgregarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<windowform.ServiceReference1.AgregarPersonaResponse> AgregarPersonaAsync(windowform.ServiceReference1.AgregarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        int EliminarPersona(int carnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminarPersonaAsync(int carnet);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersona", Namespace="http://tempuri.org/", Order=0)]
        public windowform.ServiceReference1.ModificarPersonaRequestBody Body;
        
        public ModificarPersonaRequest() {
        }
        
        public ModificarPersonaRequest(windowform.ServiceReference1.ModificarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string departamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tipo;
        
        public ModificarPersonaRequestBody() {
        }
        
        public ModificarPersonaRequestBody(int carnet, string nombre, string apellido, string departamento, string correo, string tipo) {
            this.carnet = carnet;
            this.nombre = nombre;
            this.apellido = apellido;
            this.departamento = departamento;
            this.correo = correo;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public windowform.ServiceReference1.ModificarPersonaResponseBody Body;
        
        public ModificarPersonaResponse() {
        }
        
        public ModificarPersonaResponse(windowform.ServiceReference1.ModificarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ModificarPersonaResult;
        
        public ModificarPersonaResponseBody() {
        }
        
        public ModificarPersonaResponseBody(int ModificarPersonaResult) {
            this.ModificarPersonaResult = ModificarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPersona", Namespace="http://tempuri.org/", Order=0)]
        public windowform.ServiceReference1.AgregarPersonaRequestBody Body;
        
        public AgregarPersonaRequest() {
        }
        
        public AgregarPersonaRequest(windowform.ServiceReference1.AgregarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string departamento;
        
        public AgregarPersonaRequestBody() {
        }
        
        public AgregarPersonaRequestBody(int carnet, string nombre, string apellido, string correo, string tipo, string departamento) {
            this.carnet = carnet;
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.tipo = tipo;
            this.departamento = departamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public windowform.ServiceReference1.AgregarPersonaResponseBody Body;
        
        public AgregarPersonaResponse() {
        }
        
        public AgregarPersonaResponse(windowform.ServiceReference1.AgregarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AgregarPersonaResult;
        
        public AgregarPersonaResponseBody() {
        }
        
        public AgregarPersonaResponseBody(int AgregarPersonaResult) {
            this.AgregarPersonaResult = AgregarPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : windowform.ServiceReference1.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<windowform.ServiceReference1.ServicioWebSoap>, windowform.ServiceReference1.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        windowform.ServiceReference1.ModificarPersonaResponse windowform.ServiceReference1.ServicioWebSoap.ModificarPersona(windowform.ServiceReference1.ModificarPersonaRequest request) {
            return base.Channel.ModificarPersona(request);
        }
        
        public int ModificarPersona(int carnet, string nombre, string apellido, string departamento, string correo, string tipo) {
            windowform.ServiceReference1.ModificarPersonaRequest inValue = new windowform.ServiceReference1.ModificarPersonaRequest();
            inValue.Body = new windowform.ServiceReference1.ModificarPersonaRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.departamento = departamento;
            inValue.Body.correo = correo;
            inValue.Body.tipo = tipo;
            windowform.ServiceReference1.ModificarPersonaResponse retVal = ((windowform.ServiceReference1.ServicioWebSoap)(this)).ModificarPersona(inValue);
            return retVal.Body.ModificarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<windowform.ServiceReference1.ModificarPersonaResponse> windowform.ServiceReference1.ServicioWebSoap.ModificarPersonaAsync(windowform.ServiceReference1.ModificarPersonaRequest request) {
            return base.Channel.ModificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<windowform.ServiceReference1.ModificarPersonaResponse> ModificarPersonaAsync(int carnet, string nombre, string apellido, string departamento, string correo, string tipo) {
            windowform.ServiceReference1.ModificarPersonaRequest inValue = new windowform.ServiceReference1.ModificarPersonaRequest();
            inValue.Body = new windowform.ServiceReference1.ModificarPersonaRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.departamento = departamento;
            inValue.Body.correo = correo;
            inValue.Body.tipo = tipo;
            return ((windowform.ServiceReference1.ServicioWebSoap)(this)).ModificarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        windowform.ServiceReference1.AgregarPersonaResponse windowform.ServiceReference1.ServicioWebSoap.AgregarPersona(windowform.ServiceReference1.AgregarPersonaRequest request) {
            return base.Channel.AgregarPersona(request);
        }
        
        public int AgregarPersona(int carnet, string nombre, string apellido, string correo, string tipo, string departamento) {
            windowform.ServiceReference1.AgregarPersonaRequest inValue = new windowform.ServiceReference1.AgregarPersonaRequest();
            inValue.Body = new windowform.ServiceReference1.AgregarPersonaRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.correo = correo;
            inValue.Body.tipo = tipo;
            inValue.Body.departamento = departamento;
            windowform.ServiceReference1.AgregarPersonaResponse retVal = ((windowform.ServiceReference1.ServicioWebSoap)(this)).AgregarPersona(inValue);
            return retVal.Body.AgregarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<windowform.ServiceReference1.AgregarPersonaResponse> windowform.ServiceReference1.ServicioWebSoap.AgregarPersonaAsync(windowform.ServiceReference1.AgregarPersonaRequest request) {
            return base.Channel.AgregarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<windowform.ServiceReference1.AgregarPersonaResponse> AgregarPersonaAsync(int carnet, string nombre, string apellido, string correo, string tipo, string departamento) {
            windowform.ServiceReference1.AgregarPersonaRequest inValue = new windowform.ServiceReference1.AgregarPersonaRequest();
            inValue.Body = new windowform.ServiceReference1.AgregarPersonaRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.correo = correo;
            inValue.Body.tipo = tipo;
            inValue.Body.departamento = departamento;
            return ((windowform.ServiceReference1.ServicioWebSoap)(this)).AgregarPersonaAsync(inValue);
        }
        
        public int EliminarPersona(int carnet) {
            return base.Channel.EliminarPersona(carnet);
        }
        
        public System.Threading.Tasks.Task<int> EliminarPersonaAsync(int carnet) {
            return base.Channel.EliminarPersonaAsync(carnet);
        }
    }
}
